# report_generator.py
from fpdf import FPDF
import pandas as pd
from datetime import datetime
import os

class ReportGenerator:
    def __init__(self):
        self.pdf = FPDF()
        
    def generate_risk_report(self, risk_df, summary, filename="supply_chain_risk_report.pdf"):
        """Generate PDF risk report"""
        try:
            self.pdf = FPDF()
            self.pdf.add_page()
            
            # Title
            self.pdf.set_font("Arial", "B", 16)
            self.pdf.cell(190, 10, "SUPPLY CHAIN RISK INTELLIGENCE REPORT", ln=True, align="C")
            
            # Date
            self.pdf.set_font("Arial", "I", 10)
            self.pdf.cell(190, 10, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align="R")
            self.pdf.ln(5)
            
            # Executive Summary
            self.pdf.set_font("Arial", "B", 14)
            self.pdf.cell(190, 10, "EXECUTIVE SUMMARY", ln=True)
            self.pdf.set_font("Arial", "", 12)
            
            summary_text = (
                f"• Average Supply Chain Risk: {summary.get('avg_risk', 0):.1%}\n"
                f"• Maximum Risk: {summary.get('max_risk', 0):.1%}\n"
                f"• High-Risk Suppliers: {summary.get('high_risk_count', 0)}\n"
                f"• Total Financial Exposure at Risk: ${summary.get('total_exposure', 0):,.0f}\n"
            )
            self.pdf.multi_cell(190, 8, summary_text)
            self.pdf.ln(5)
            
            # High Risk Suppliers
            if not risk_df.empty:
                self.pdf.set_font("Arial", "B", 14)
                self.pdf.cell(190, 10, "CRITICAL SUPPLIERS", ln=True)
                self.pdf.set_font("Arial", "B", 9)
                
                cols = ['Name', 'Country', 'Industry', 'Risk Score', 'Exposure ($)']
                col_widths = [45, 30, 30, 30, 45]
                
                for i, col in enumerate(cols):
                    self.pdf.cell(col_widths[i], 10, col, border=1)
                self.pdf.ln()
                
                self.pdf.set_font("Arial", "", 8)
                high_risk = risk_df[risk_df['risk_score'] >= 0.6].head(10)
                for _, row in high_risk.iterrows():
                    self.pdf.cell(col_widths[0], 8, str(row.get('name', ''))[:18], border=1)
                    self.pdf.cell(col_widths[1], 8, str(row.get('country', ''))[:12], border=1)
                    self.pdf.cell(col_widths[2], 8, str(row.get('industry', ''))[:12], border=1)
                    self.pdf.cell(col_widths[3], 8, f"{row.get('risk_score', 0):.1%}", border=1)
                    self.pdf.cell(col_widths[4], 8, f"${row.get('exposure_at_risk_usd', 0):,.0f}", border=1)
                    self.pdf.ln()
            
            self.pdf.ln(5)
            
            # Risk Distribution
            self.pdf.set_font("Arial", "B", 14)
            self.pdf.cell(190, 10, "RISK DISTRIBUTION", ln=True)
            self.pdf.set_font("Arial", "", 10)
            
            dist = summary.get('risk_distribution', {})
            if dist:
                dist_text = (
                    f"Minimum: {dist.get('min', 0):.1%}\n"
                    f"25th Percentile: {dist.get('25%', 0):.1%}\n"
                    f"Median: {dist.get('50%', 0):.1%}\n"
                    f"75th Percentile: {dist.get('75%', 0):.1%}\n"
                    f"Maximum: {dist.get('max', 0):.1%}\n"
                )
                self.pdf.multi_cell(190, 6, dist_text)
            
            # Footer
            self.pdf.set_y(250)
            self.pdf.set_font("Arial", "I", 8)
            self.pdf.cell(190, 10, "Generated by Supply Chain Defender v1.0", align="C")
            
            self.pdf.output(filename)
            return filename
            
        except Exception as e:
            print(f"Report generation error: {e}")
            return None
